### ISSUE TITLE
1.16.5崩溃，无法启动

### ISSUE THREAD

**Issue by WZdaze** [AkvamaroGlacirivero/EnchantIcon#2]
PCL显示需要前置，但加了之后依然崩溃
![3FZK~~%7 NQ5{_I9)Q 9(NR](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/51307715/d081df91-3339-4d73-8887-e74dad7df92d)
[latest.log](https://github.com/AkvamaroGlacirivero/EnchantIcon/files/13766849/latest.log)

**Comment by WZdaze** [comment]
错误报告补充
[错误报告-2023-12-26_1.13.57.zip](https://github.com/AkvamaroGlacirivero/EnchantIcon/files/13766855/-2023-12-26_1.13.57.zip)

**Comment by AkvamaroGlacirivero** [comment]
https://github.com/AkvamaroGlacirivero/EnchantIcon/commit/1dd959b42c9cc45acfbef310e9907658eebf50b3

Check CurseForge / Modrinth for new versions.
