### ISSUE TITLE
Config does not have effect

### ISSUE THREAD

**Issue by qznfbnj** [AkvamaroGlacirivero/EnchantIcon#3]
## 模组列表
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/b58d4fa8-0577-4e64-8883-496789ab0e72)

## 问题
不知道是不是Forge的问题，每次不管怎么改，实际文件已经改了，进配置界面都是默认配置，而游戏中仍是启动游戏时的配置

![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/6967d2d7-0554-4dcf-937f-7e9a5b9aaf51)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/8a5fd153-1ebb-45e7-bf52-252525c33934)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/0c4643a7-cafe-458c-a426-d416f4048024)

**Comment by qznfbnj** [comment]
用Cloth Config API就不行，用Forge Config Screens就可以实时修改
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/e2c14aef-5a3f-4784-be69-e790c0768397)

**Comment by AkvamaroGlacirivero** [comment]
https://modrinth.com/mod/enchant-icon/version/cscNqUdJ 

这个版本是否工作？

**Comment by qznfbnj** [comment]
变成这样
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/af06713d-630f-4196-b284-96398381720b)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/cafea566-ffad-44c2-8e5e-f03ddacb9d15)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/65feb1dc-c1c8-4c02-a36c-3c96deccecfb)

**Comment by AkvamaroGlacirivero** [comment]
https://modrinth.com/mod/enchant-icon/version/iqWDf5AZ

请告诉我这一版本是否有效.

**Comment by qznfbnj** [comment]
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/181abce7-22e4-459b-8965-c923df9badc5)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/5c0552b5-2690-4af0-8af0-479d07fe0d42)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/3468c67f-f7d2-48ca-bec1-60746c6c283d)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/7286aee8-2700-4414-ade9-e6a46dd79a95)
还是那样，不过至少配置界面和实际文件能对应上了。
重新开了个实例也一样。Forge升级了还是一样。JDK18换回JDK17也一样。PrismLauncher换成PCL2也一样。
~~不过一路测试下来似乎发现，在更改完scope设置后，确认返回暂停界面，再打开配置界面，修改 Level Mark Type，有几率在游戏中生效，原因未知。~~ 感觉更改会不会生效还是随机的
最近一次成功更改设置：
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/5109c3bd-155a-4735-85ef-77a1f8518c0a)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/cc428e2d-c47b-4062-b57b-d16d7b63c39f)

**Comment by AkvamaroGlacirivero** [comment]
Change title for future reference.

------

Still cannot reproduce on my machine. Dunno why.

**Comment by AkvamaroGlacirivero** [comment]
https://modrinth.com/mod/enchant-icon/version/SKqGLqdS

请告诉我这一版本是否修复了问题.

**Comment by qznfbnj** [comment]
看起来能生效了
## test1
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/7d0ec907-e13f-4e76-b41c-309805185821)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/f46162b3-59e0-4d65-aa42-7da26f053166)
## test2
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/21a3f0d8-eab9-4d88-acec-96b39e14d392)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/68d8a732-8297-433b-b518-6eff5a85b9a2)

**Comment by AkvamaroGlacirivero** [comment]
https://github.com/AkvamaroGlacirivero/EnchantIcon/commit/f081626777c4602f1cfe4fc15054f01d5f6aeea2

https://github.com/AkvamaroGlacirivero/EnchantIcon/commit/cb682f1292892949d450e0713235ec4469af936d

The issue should have been fixed for all versions starting from `1.1.0-11`. Hopefully. 

Check CurseForge / Modrinth for new release.

**Comment by qznfbnj** [comment]
其实原标题之所以指明 Forge，是因为 Fabric 上就算 1.0.1-3 都没有这个问题hhh
In fact, the reason why the original title specified Forge is because there is no such problem on Fabric even using 1.0.1-3 lol
