### ISSUE TITLE
物品贴图问题

### ISSUE THREAD

**Issue by qznfbnj** [AkvamaroGlacirivero/EnchantIcon#4]
按住显示附魔标签的快捷键时，指南针、追溯指针、时钟的纹理会静止，这是故意的吗？
偶然发现其他模组的物品也会这样，比如夸克的算盘、寻路羽毛笔，Deeper and Darker的幽匿传讯器等
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/707ff8ec-2bd5-427e-a8bd-28b63203c77c)
![image](https://github.com/AkvamaroGlacirivero/EnchantIcon/assets/100760086/ae0e6bac-204a-48bc-b8c4-4f4ef8b29117)

**Comment by AkvamaroGlacirivero** [comment]
Not intended. I will look into it.

**Comment by AkvamaroGlacirivero** [comment]
https://github.com/AkvamaroGlacirivero/EnchantIcon/commit/3303bc2fa0a67239fbd4a145283bbaa981ec6d46

Check CurseForge / Modrinth for new versions.
